name: CI/CD - Blog Artigos

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Validar código e build
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Rodar ESLint
        run: npm run lint

      - name: Rodar testes
        run: npm run test

      - name: Rodar build
        run: npm run build